// Date: 11/9/2013 8:59:14 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package darva.shadowcraft.models;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ShadowCloak extends ModelBiped
{
  //fields
    ModelRenderer Collar_Base;
    ModelRenderer Collar_Outer_1;
    ModelRenderer Collar_Outer_2;
    ModelRenderer Collar_Back;
    ModelRenderer Cloak_Main;
    ModelRenderer Cloak_Bottom;
    ModelRenderer Collar_inner_1;
    ModelRenderer collar_inner_2;
  
  public ShadowCloak()
  {
	  super(1,0,64,64);
    textureWidth = 64;
    textureHeight = 64;
    
    
      Collar_Base = new ModelRenderer(this, 19, 51);
      Collar_Base.addBox(-5F, 0F, 0F, 10, 1, 4);
      Collar_Base.setRotationPoint(0F, 0F, 2F);
      Collar_Base.setTextureSize(64, 64);
      Collar_Base.mirror = true;
      setRotation(Collar_Base, 0F, 0F, 0F);
      Collar_Outer_1 = new ModelRenderer(this, 19, 43);
      Collar_Outer_1.addBox(5F, -2F, 3F, 1, 4, 3);
      Collar_Outer_1.setRotationPoint(0F, 0F, 0F);
      Collar_Outer_1.setTextureSize(64, 64);
      Collar_Outer_1.mirror = true;
      setRotation(Collar_Outer_1, 0F, 0F, 0F);
      Collar_Outer_2 = new ModelRenderer(this, 28, 43);
      Collar_Outer_2.addBox(-6F, -2F, 3F, 1, 4, 3);
      Collar_Outer_2.setRotationPoint(0F, 0F, 0F);
      Collar_Outer_2.setTextureSize(64, 64);
      Collar_Outer_2.mirror = true;
      setRotation(Collar_Outer_2, 0F, 0F, 0F);
      Collar_Back = new ModelRenderer(this, 0, 33);
      Collar_Back.addBox(-5F, -6F, 5F, 10, 6, 1);
      Collar_Back.setRotationPoint(0F, 0F, 0F);
      Collar_Back.setTextureSize(64, 64);
      Collar_Back.mirror = true;
      setRotation(Collar_Back, 0F, 0F, 0F);
      Cloak_Main = new ModelRenderer(this, 0, 41);
      Cloak_Main.addBox(-4F, 1F, 5F, 8, 11, 1);
      Cloak_Main.setRotationPoint(0F, 0F, 0F);
      Cloak_Main.setTextureSize(64, 64);
      Cloak_Main.mirror = true;
      setRotation(Cloak_Main, 0F, 0F, 0F);
      Cloak_Bottom = new ModelRenderer(this, 23, 33);
      Cloak_Bottom.addBox(-6F, 12F, 5F, 12, 8, 1);
      Cloak_Bottom.setRotationPoint(0F, 0F, 0F);
      Cloak_Bottom.setTextureSize(64, 64);
      Cloak_Bottom.mirror = true;
      setRotation(Cloak_Bottom, 0F, 0F, 0F);
      Collar_inner_1 = new ModelRenderer(this, 51, 39);
      Collar_inner_1.addBox(-6F, -1F, -1F, 1, 1, 4);
      Collar_inner_1.setRotationPoint(0F, 0F, 0F);
      Collar_inner_1.setTextureSize(64, 64);
      Collar_inner_1.mirror = true;
      setRotation(Collar_inner_1, 0F, 0F, 0F);
      collar_inner_2 = new ModelRenderer(this, 51, 33);
      collar_inner_2.addBox(5F, -1F, -1F, 1, 1, 4);
      collar_inner_2.setRotationPoint(0F, 0F, 0F);
      collar_inner_2.setTextureSize(64, 64);
      collar_inner_2.mirror = true;
      setRotation(collar_inner_2, 0F, 0F, 0F);
      
      this.bipedBody.addChild(Cloak_Bottom);
      this.bipedBody.addChild(Cloak_Main);
      this.bipedBody.addChild(Collar_Back);
      this.bipedBody.addChild(Collar_Base);
      this.bipedBody.addChild(Collar_Outer_1);
      this.bipedBody.addChild(Collar_Outer_2);
      this.bipedBody.addChild(Collar_inner_1);
      this.bipedBody.addChild(collar_inner_2);
  }
  
  /* (non-Javadoc)
 * @see net.minecraft.client.model.ModelBiped#setRotationAngles(float, float, float, float, float, float, net.minecraft.entity.Entity)
 */
@Override
public void setRotationAngles(float par1, float par2, float par3, float par4,
		float par5, float par6, Entity par7Entity) {
	// TODO Auto-generated method stub
	super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
}

public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Collar_Base.render(f5);
    Collar_Outer_1.render(f5);
    Collar_Outer_2.render(f5);
    Collar_Back.render(f5);
    Cloak_Main.render(f5);
    Cloak_Bottom.render(f5);
    Collar_inner_1.render(f5);
    collar_inner_2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  

}
